# Generated by Django 6.0.4 on 2026-04-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.FloatField()),
                ('day', models.CharField(max_length=10)),
                ('period', models.FloatField()),
                ('nsw_price', models.FloatField(db_column='nswprice')),
                ('nsw_demand', models.FloatField(db_column='nswdemand')),
                ('vic_price', models.FloatField(db_column='vicprice')),
                ('vic_demand', models.FloatField(db_column='vicdemand')),
                ('transfer', models.FloatField()),
                ('demand_class', models.CharField(db_column='class', max_length=10)),
            ],
            options={
                'db_table': 'electricity_records',
                'ordering': ['date', 'period'],
            },
        ),
    ]
