# Generated by Django 6.0.4 on 2026-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityrecord',
            name='day',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='electricityrecord',
            name='demand_class',
            field=models.CharField(db_column='class', db_index=True, max_length=10),
        ),
    ]
